config/routes.rb
Rails.application.routes.draw do
  resources :songs
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, :artist, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if session[:user_id]
      redirect_to songs_path
    end
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "#{user.username} signed in successfully."
      redirect_to songs_path
    else
      flash[:notice] = 'You are wrong.'
      render :new
    end
  end

  def destroy
    username = current_user.username
    session.clear
    flash[:notice] = "#{username} signed out successfully."
    redirect_to login_path
  end
end

app/controllers/songs_controller.rb
# song controller
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = []
    @songs = current_user.songs if current_user

  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    song = Song.new(song_params)
    song.user_id = session[:user_id]
    if song.save
      redirect_to song
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :artist)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= flash[:notice] %>
    <% if current_user %>
      <%= link_to "Log out", logout_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :artist %>
  <%= f.text_field :artist %>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<p>edit</p>
<%= render 'form' %>

app/views/songs/index.html.erb
<h1>Hello <%= current_user.username if current_user %>.</h1>
<% @songs.each do |song| %>
  <p><%= link_to song.title, song %></p>
<% end %>

<p><%= link_to 'New Song', new_song_path %></p>

app/views/songs/new.html.erb
<h1>create a new song</h1>
<%= render 'form' %>

app/views/songs/show.html.erb
<p> hi </p>
<h1><%= @song.title %></h1>
<p><%= @song.artist %></p>
<%= link_to "Songs", songs_path %>
<%= link_to "Edit", edit_song_path(@song) %>
<%= link_to "Delete", song_path(@song), method: :delete %>

app/views/songs/whydoesnthiswork.html.erb
hello